//import { SortingDirection } from "igniteui-angular/lib/data-operations/sorting-strategy";
//import { IgxGridComponent } from "igniteui-angular/lib/grids/grid/grid.component";

export const Constants = {
  SurveyConsoleColumnHeader: [
    {
      header: 'Order',
      abbreviation: 'Part Name',
      value: 'Order',
      dataType: 'string',
      input: '',
      checked: true,
      width: '',  // Fixed width
      minWidth: '', // Minimum width as a percentage
      isActive: true,
    },
    {
      header: 'Description',
      abbreviation: 'Part #',
      value: 'Description',
      dataType: 'string',
      input: '',
      checked: true,
      width: '',  // Fixed width
      minWidth: '',  // Minimum width as a percentage
      isActive: true,
    },
    {
      header: 'Questions',
      abbreviation: 'Assigned To',
      value: 'Question',
      dataType: 'string',
      input: '',
      checked: true,
      width: '',  // Fixed width
      minWidth: '', // Minimum width as a percentage
      isActive: true,
    },
    {
      header: '',
      abbreviation: '',
      value: 'icons',
      dataType: '',
      width: '20px',   // Fixed width for icons
      minWidth: '5%',  // Minimum width as a percentage
      checked: true,
      isActive: true,
    },
  ]
  ,

  InterviewConsoleColumnHeader: [
    {
      header: 'Order',
      abbreviation: 'Part Name',
      value: 'order',
      dataType: 'string',
      input: '',
      checked: true,
      width: '5%',
      minWidth: '12%',
      isActive: false,
    },
    {
      header: 'Description',
      abbreviation: 'Part #',
      value: 'description',
      dataType: 'string',
      input: '',
      checked: true,
      width: '8%',
      minWidth: '12%',
      isActive: false,
    },
    {
      header: 'Questions',
      abbreviation: 'Assigned To',
      value: 'question',
      dataType: 'string',
      input: '',
      checked: true,
      width: '82%',
      minWidth: '12%',
      isActive: false,
    },
    {
      header: '',
      abbreviation: '',
      value: 'icons',
      dataType: '',
      width: '5%',
      minWidth: '5%',
      checked: true,
      isActive: false,
    },
  ],

  QuizConsoleColumnHeader: [
    {
      header: 'Order',
      abbreviation: 'Part Name',
      value: 'order',
      dataType: 'string',
      input: '',
      checked: true,
      width: '5%',
      minWidth: '12%',
      isActive: false,
    },
    {
      header: 'Description',
      abbreviation: 'Part #',
      value: 'description',
      dataType: 'string',
      input: '',
      checked: true,
      width: '8%',
      minWidth: '12%',
      isActive: false,
    },
    {
      header: 'Points',
      abbreviation: 'Points',
      value: 'points',
      dataType: 'number',
      input: '',
      checked: true,
      width: '5%',
      minWidth: '5%',
      isActive: false,
    },
    {
      header: 'Weight',
      abbreviation: 'Weight',
      value: 'weight',
      dataType: 'string',
      input: '',
      checked: true,
      width: '5%',
      minWidth: '5%',
      isActive: false,
    },
    {
      header: 'Questions',
      abbreviation: 'Assigned To',
      value: 'question',
      dataType: 'string',
      input: '',
      checked: true,
      width: '72%',
      minWidth: '12%',
      isActive: false,
    },
    {
      header: '',
      abbreviation: '',
      value: 'icons',
      dataType: '',
      width: '5%',
      minWidth: '5%',
      checked: true,
      isActive: false,
    },
  ],

  AnswerFieldsColumnHeader: [
    {
      header: 'ID',
      abbreviation: 'ID',
      value: 'id',
      dataType: 'string',
      input: '',
      checked: true,
      width: '5%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Label',
      abbreviation: 'Label',
      value: 'label',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '10%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Field',
      abbreviation: 'Field',
      value: 'field',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '10%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Input Type',
      abbreviation: 'Input Type',
      value: 'inputType',
      dataType: 'string',
      input: '',
      checked: true,
      width: '12%',
      minWidth: '10%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Created',
      abbreviation: 'Created',
      value: 'created',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '9%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Updated',
      abbreviation: 'Updated',
      value: 'updated',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '9%',
      isActive: false,
      showFilter: true,
    },
    {
      header: '',
      abbreviation: '',
      value: 'icons',
      dataType: '',
      width: '5.2%',
      minWidth: '5%',
      checked: true,
      isActive: false,
      showFilter: false,
    },
  ],

  SurveyTypesColumnHeader: [
    {
      header: 'ID #',
      abbreviation: 'ID #',
      value: 'id',
      dataType: 'number',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Type',
      abbreviation: 'Type',
      value: 'type',
      dataType: 'string',
      input: '',
      checked: true,
      width: '22%',
      minWidth: '11%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Default',
      abbreviation: 'Default',
      value: 'default',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Enabled',
      abbreviation: 'Enabled',
      value: 'enabled',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Environment',
      abbreviation: 'Environment',
      value: 'environment',
      dataType: 'string',
      input: '',
      checked: true,
      width: '8%',
      minWidth: '4%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Created',
      abbreviation: 'Created',
      value: 'created',
      dataType: 'date',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '18%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Updated',
      abbreviation: 'Updated',
      value: 'updated',
      dataType: 'date',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '18%',
      isActive: false,
      showFilter: true,
    },
    {
      header: '',
      abbreviation: 'Clone',
      value: 'clone',
      dataType: 'blank',
      input: '',
      checked: true,
      width: '5.15%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
    },
    // {
    //   header: '',
    //   abbreviation: '',
    //   value: '',
    //   dataType: '',
    //   input: '',
    //   checked: true,
    // },
  ],

  InterviewTypesColumnHeader: [
    {
      header: 'ID #',
      abbreviation: 'ID #',
      value: 'id',
      dataType: 'number',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Type',
      abbreviation: 'Type',
      value: 'type',
      dataType: 'string',
      input: '',
      checked: true,
      width: '22%',
      minWidth: '11%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Default',
      abbreviation: 'Default',
      value: 'default',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Enabled',
      abbreviation: 'Enabled',
      value: 'enabled',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Environment',
      abbreviation: 'Environment',
      value: 'environment',
      dataType: 'string',
      input: '',
      checked: true,
      width: '8%',
      minWidth: '4%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Created',
      abbreviation: 'Created',
      value: 'created',
      dataType: 'date',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '12%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Updated',
      abbreviation: 'Updated',
      value: 'updated',
      dataType: 'date',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '12%',
      isActive: false,
      showFilter: true,
    },
    {
      header: '',
      abbreviation: 'Clone',
      value: 'clone',
      dataType: 'blank',
      input: '',
      checked: true,
      width: '5.2%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
    },
    {
      header: '',
      abbreviation: '',
      value: '',
      dataType: '',
      input: '',
      checked: true,
    },
  ],

  QuizTypesColumnHeader: [
    {
      header: 'ID #',
      abbreviation: 'ID #',
      value: 'id',
      dataType: 'number',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Name',
      abbreviation: 'Name',
      value: 'type',
      dataType: 'string',
      input: '',
      checked: true,
      width: '22%',
      minWidth: '11%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Default',
      abbreviation: 'Default',
      value: 'default',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Passthreshold',
      abbreviation: 'Passthreshold',
      value: 'passThreshold',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Enabled',
      abbreviation: 'Enabled',
      value: 'enabled',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Environment',
      abbreviation: 'Environment',
      value: 'environment',
      dataType: 'string',
      input: '',
      checked: true,
      width: '8%',
      minWidth: '4%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Created',
      abbreviation: 'Created',
      value: 'created',
      dataType: 'date',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '12%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Updated',
      abbreviation: 'Updated',
      value: 'updated',
      dataType: 'date',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '12%',
      isActive: false,
      showFilter: true,
    },
    {
      header: '',
      abbreviation: 'Clone',
      value: 'clone',
      dataType: 'blank',
      input: '',
      checked: true,
      width: '5%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
    },
    {
      header: '',
      abbreviation: '',
      value: '',
      dataType: '',
      input: '',
      checked: true,
      width: '4.2%',
      minWidth: '3%',
    },
  ],

  TenantSurveyHistoryColumnHeader: [
    {
      header: 'Logs',
      abbreviation: 'Logs',
      value: 'logs',
      dataType: 'blank',
      input: '',
      checked: false,
      width: '4%',
      minWidth: '4%',
      isActive: false,
      showFilter: false,
    },
    {
      header: '',
      abbreviation: '',
      value: 'check',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '3%',
      minWidth: '3%',
      isActive: false,
      isHeaderCheckBox: true,
      showFilter: false,
      isCustomColumn: true,
    },
    {
      header: 'Tenant',
      abbreviation: 'Tenant',
      value: 'tenantName',
      dataType: 'string',
      input: '',
      checked: false,
      width: '10%',
      minWidth: '10%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Session',
      abbreviation: 'AR #',
      value: 'ar',
      dataType: 'string',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Type',
      abbreviation: 'Type',
      value: 'type',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '10%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'User',
      abbreviation: 'User',
      value: 'user',
      dataType: 'string',
      input: '',
      checked: true,
      width: '8%',
      minWidth: '8%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Location',
      abbreviation: 'Location',
      value: 'location',
      dataType: 'string',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '15%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Video',
      abbreviation: 'Video',
      value: 'video',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '6%',
      minWidth: '6%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
      //showIcons:true,
    },
    {
      header: 'Pass/Fail',
      abbreviation: 'Pass/Fail',
      value: 'passOrFail',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '6%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
      //showIcons:true,
    },
    {
      header: 'Stopped',
      abbreviation: 'Stopped',
      value: 'stopped',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '6%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
      //showIcons:true,
    },
    {
      header: 'Complete',
      abbreviation: 'Complete',
      value: 'complete',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '6%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
      //showIcons:true,
    },
    {
      header: 'Creation Date',
      abbreviation: 'Creation Date',
      value: 'creationDate',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '15%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      sendFilterData: true,
    },
    {
      header: 'Upload Date',
      abbreviation: 'Upload Date',
      value: 'uploadDate',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '15%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      sendFilterData: true,
    },
    {
      header: 'Upload From',
      abbreviation: 'Upload From',
      value: 'uploadFrom',
      dataType: 'string',
      input: '',
      checked: false,
      width: '10%',
      minWidth: '10%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'File Size',
      abbreviation: 'File Size',
      value: 'fileSize',
      dataType: 'string',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Platform',
      abbreviation: 'Platform',
      value: 'platform',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Device',
      abbreviation: 'Device',
      value: 'device',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'App Ver.',
      abbreviation: 'App Ver.',
      value: 'appVer',
      dataType: 'string',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'OS Ver.',
      abbreviation: 'OS Ver.',
      value: 'osVer',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Battery %',
      abbreviation: 'Battery %',
      value: 'battery',
      dataType: 'number',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'ISP Speed',
      abbreviation: 'ISP Speed',
      value: 'ispSpeed',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'CRM Upload',
      abbreviation: 'CRM Upload',
      value: 'crmUpload',
      dataType: 'boolean',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
  ],

  TenantInterviewHistoryColumnHeader: [
    {
      header: '',
      abbreviation: '',
      value: 'check',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '3%',
      minWidth: '3%',
      isActive: false,
      isHeaderCheckBox: true,
      showFilter: false,
      isCustomColumn: true,
    },
    {
      header: 'Session',
      abbreviation: 'AR #',
      value: 'ar',
      dataType: 'string',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Type',
      abbreviation: 'Type',
      value: 'type',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'User',
      abbreviation: 'User',
      value: 'user',
      dataType: 'string',
      input: '',
      checked: true,
      width: '8%',
      minWidth: '4%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Location',
      abbreviation: 'Location',
      value: 'location',
      dataType: 'string',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '8%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Video',
      abbreviation: 'Video',
      value: 'video',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '6%',
      minWidth: '6%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Pass/Fail',
      abbreviation: 'Pass/Fail',
      value: 'passOrFail',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Stopped',
      abbreviation: 'Stopped',
      value: 'stopped',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Complete',
      abbreviation: 'Complete',
      value: 'complete',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Creation Date',
      abbreviation: 'Creation Date',
      value: 'creationDate',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      sendFilterData: true,
    },
    {
      header: 'Upload Date',
      abbreviation: 'Upload Date',
      value: 'uploadDate',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      sendFilterData: true,
    },
    {
      header: 'Upload From',
      abbreviation: 'Upload From',
      value: 'uploadFrom',
      dataType: 'string',
      input: '',
      checked: false,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'File Size',
      abbreviation: 'File Size',
      value: 'fileSize',
      dataType: 'number',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Platform',
      abbreviation: 'Platform',
      value: 'platform',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Device',
      abbreviation: 'Device',
      value: 'device',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'App Ver.',
      abbreviation: 'App Ver.',
      value: 'appVer',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'OS Ver.',
      abbreviation: 'OS Ver.',
      value: 'osVer',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Battery %',
      abbreviation: 'Battery %',
      value: 'battery',
      dataType: 'number',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'ISP Speed',
      abbreviation: 'ISP Speed',
      value: 'ispSpeed',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'CRM Upload',
      abbreviation: 'CRM Upload',
      value: 'crmUpload',
      dataType: 'boolean',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: '',
      abbreviation: '',
      value: '',
      dataType: '',
      input: '',
      checked: true,
      width: '',
      minWidth: '',
      isActive: false,
      isHeaderCheckBox: false,
    },
  ],

  TenantQuizHistoryColumnHeader: [
    {
      header: '',
      abbreviation: '',
      value: 'check',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '3%',
      minWidth: '3%',
      isActive: false,
      isHeaderCheckBox: true,
      showFilter: false,
      isCustomColumn: true,
    },
    {
      header: 'Session',
      abbreviation: 'AR #',
      value: 'ar',
      dataType: 'string',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Type',
      abbreviation: 'Type',
      value: 'type',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'User',
      abbreviation: 'User',
      value: 'user',
      dataType: 'string',
      input: '',
      checked: true,
      width: '8%',
      minWidth: '4%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Location',
      abbreviation: 'Location',
      value: 'location',
      dataType: 'string',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '8%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Video',
      abbreviation: 'Video',
      value: 'video',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Pass/Fail',
      abbreviation: 'Pass/Fail',
      value: 'passOrFail',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Stopped',
      abbreviation: 'Stopped',
      value: 'stopped',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Complete',
      abbreviation: 'Complete',
      value: 'complete',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Score',
      abbreviation: 'Score',
      value: 'score',
      dataType: 'number',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Creation Date',
      abbreviation: 'Creation Date',
      value: 'creationDate',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      sendFilterData: true,
    },
    {
      header: 'Upload Date',
      abbreviation: 'Upload Date',
      value: 'uploadDate',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      sendFilterData: true,
    },
    {
      header: 'Upload From',
      abbreviation: 'Upload From',
      value: 'uploadFrom',
      dataType: 'string',
      input: '',
      checked: false,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'File Size',
      abbreviation: 'File Size',
      value: 'fileSize',
      dataType: 'number',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Platform',
      abbreviation: 'Platform',
      value: 'platform',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Device',
      abbreviation: 'Device',
      value: 'device',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'App Ver.',
      abbreviation: 'App Ver.',
      value: 'appVer',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'OS Ver.',
      abbreviation: 'OS Ver.',
      value: 'osVer',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Battery %',
      abbreviation: 'Battery %',
      value: 'battery',
      dataType: 'number',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'ISP Speed',
      abbreviation: 'ISP Speed',
      value: 'ispSpeed',
      dataType: 'string',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'CRM Upload',
      abbreviation: 'CRM Upload',
      value: 'crmUpload',
      dataType: 'boolean',
      input: '',
      checked: false,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: '',
      abbreviation: '',
      value: '',
      dataType: '',
      input: '',
      checked: true,
      width: '',
      minWidth: '',
      isActive: false,
      isHeaderCheckBox: false,
    },
  ],

  BillingConsoleColumnHeader: [
    {
      header: 'Tenants',
      abbreviation: 'Tenant Name',
      value: 'tenantName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '12%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Invoice Number',
      abbreviation: 'Invoice Number',
      value: 'invoiceNumber',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Billing Start Date',
      abbreviation: 'Billing Start Date',
      value: 'billingDateStart',
      dataType: 'date',
      input: '',
      checked: true,
      width: '16%',
      hideTime: true,
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Billing End Date',
      abbreviation: 'Billing End Date',
      value: 'billingDateEnd',
      dataType: 'date',
      input: '',
      checked: true,
      width: '16%',
      hideTime: true,
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Total Billing Amount',
      abbreviation: 'Total Billing Amount',
      value: 'totalBillingAmount',
      dataType: 'number',
      input: '',
      checked: true,
      width: '11%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Balance Amount',
      abbreviation: 'Balance Amount',
      value: 'balanceAmount',
      dataType: 'number',
      input: '',
      checked: true,
      width: '11%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Created',
      abbreviation: 'Created',
      value: 'creationTime',
      dataType: 'date',
      input: '',
      checked: true,
      width: '12%',
      hideTime: true,
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Invoice Paid',
      abbreviation: 'Invoice Paid',
      value: 'invoicePaid',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '8%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: false,
      showIcons: true,
    },
    // {
    //   header: 'Storage Billing Amount',
    //   abbreviation: 'Storage Billing Amount',
    //   value: 'storageBillingAmount',
    //   dataType: 'number',
    //   input: '',
    //   checked: false,
    //   width: '12%',
    //   isActive: false,
    //   isHeaderCheckBox: false,
    //   showFilter: true,
    // },
    // {
    //   header: 'Total Surveys',
    //   abbreviation: 'Total Surveys',
    //   value: 'totalSurveys',
    //   dataType: 'string',
    //   input: '',
    //   checked: false,
    //   width: '12%',
    //   isActive: false,
    //   isHeaderCheckBox: false,
    //   showFilter: true,
    // },
    // {
    //   header: 'Survey Storage',
    //   abbreviation: 'Survey Storage',
    //   value: 'surveyStorage',
    //   dataType: 'string',
    //   input: '',
    //   checked: false,
    //   width: '12%',
    //   isActive: false,
    //   isHeaderCheckBox: false,
    //   showFilter: true,
    // },
    // {
    //   header: 'Survey Billing Amount',
    //   abbreviation: 'Survey Billing Amount',
    //   value: 'surveyBillingAmount',
    //   dataType: 'number',
    //   input: '',
    //   checked: false,
    //   width: '12%',
    //   isActive: false,
    //   isHeaderCheckBox: false,
    //   showFilter: true,
    // },
    // {
    //   header: 'Total Quizzes',
    //   abbreviation: 'Total Quizzes',
    //   value: 'totalQuizzes',
    //   dataType: 'string',
    //   input: '',
    //   checked: false,
    //   width: '12%',
    //   isActive: false,
    //   isHeaderCheckBox: false,
    //   showFilter: true,
    // },
    // {
    //   header: 'Quiz Storage',
    //   abbreviation: 'Quiz Storage',
    //   value: 'quizStorage',
    //   dataType: 'string',
    //   input: '',
    //   checked: false,
    //   width: '12%',
    //   isActive: false,
    //   isHeaderCheckBox: false,
    //   showFilter: true,
    // },
    // {
    //   header: 'Quiz Billing Amount',
    //   abbreviation: 'Quiz Billing Amount',
    //   value: 'quizBillingAmount',
    //   dataType: 'number',
    //   input: '',
    //   checked: false,
    //   width: '12%',
    //   isActive: false,
    //   isHeaderCheckBox: false,
    //   showFilter: true,
    // },
    // {
    //   header: 'Total Interviews',
    //   abbreviation: 'Total Interviews',
    //   value: 'totalInterviews',
    //   dataType: 'string',
    //   input: '',
    //   checked: false,
    //   width: '12%',
    //   isActive: false,
    //   isHeaderCheckBox: false,
    //   showFilter: true,
    // },
    // {
    //   header: 'Interview Storage',
    //   abbreviation: 'Interview Storage',
    //   value: 'interviewStorage',
    //   dataType: 'string',
    //   input: '',
    //   checked: false,
    //   width: '12%',
    //   isActive: false,
    //   isHeaderCheckBox: false,
    //   showFilter: true,
    // },
    // {
    //   header: 'Interview Billing Amount',
    //   abbreviation: 'Interview Billing Amount',
    //   value: 'interviewBillingAmount',
    //   dataType: 'number',
    //   input: '',
    //   checked: false,
    //   width: '12%',
    //   isActive: false,
    //   isHeaderCheckBox: false,
    //   showFilter: true,
    // },
  ],

  BillingInvoiceColumnHeader: [
    {
      header: 'AR #',
      abbreviation: 'AR #',
      value: 'ar',
      dataType: 'string',
      input: '',
      checked: true,
      width: '7%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Category',
      abbreviation: 'Category',
      value: 'category',
      dataType: 'string',
      input: '',
      checked: true,
      width: '8%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'User',
      abbreviation: 'User',
      value: 'user',
      dataType: 'string',
      input: '',
      checked: true,
      width: '8%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Type',
      abbreviation: 'Type',
      value: 'type',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Location',
      abbreviation: 'Location',
      value: 'location',
      dataType: 'string',
      input: '',
      checked: true,
      width: '30%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Created',
      abbreviation: 'Created',
      value: 'created',
      dataType: 'date',
      input: '',
      checked: true,
      width: '16%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
  ],

  DemoUsersColumnHeaders: [
    {
      header: 'Session ID',
      abbreviation: 'Session ID',
      value: 'id',
      dataType: 'number',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Demo Username',
      abbreviation: 'Link Name',
      value: 'linkName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Created',
      abbreviation: 'Created',
      value: 'created',
      dataType: 'date',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
    },
    {
      header: 'Enabled',
      abbreviation: 'Enabled',
      value: 'enabled',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: '',
      abbreviation: 'icons',
      value: 'icons',
      dataType: 'blank',
      input: '',
      checked: true,
      width: '10.2%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
    },
  ],

  ChangeLogsColumnHeader: [
    {
      header: 'Table Name',
      abbreviation: 'Table Name',
      value: 'tableName',
      dataType: 'string',
      width: '12%',
      checked: true,
      minWidth: '7%',
      showFilter: true,
    },
    {
      header: 'Change Type Name',
      abbreviation: 'Change Type Name',
      value: 'changeTypeName',
      dataType: 'string',
      input: '',
      width: '12%',
      minWidth: '7%',
      checked: true,
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Property Name',
      abbreviation: 'Property Name',
      value: 'propertyName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '17%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },

    {
      header: 'Original Value',
      abbreviation: 'Original Value',
      value: 'originalValue',
      dataType: 'string',
      input: '',
      checked: true,
      width: '12%',
      minWidth: '4%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'New Value',
      abbreviation: 'New Value',
      value: 'newValue',
      dataType: 'string',
      input: '',
      checked: true,
      width: '17%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Changed By',
      abbreviation: 'Changed By',
      value: 'changedBy',
      dataType: 'string',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Change Time',
      abbreviation: 'Change Time',
      value: 'changeTime',
      dataType: 'date',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '9%',
      isActive: false,
      showFilter: true,
    },
  ],

  TenantChangeLogsColumnHeader: [
    {
      header: 'Tenant Name',
      abbreviation: 'Tenant Name',
      value: 'tenantName',
      dataType: 'string',
      checked: true,
      width: '12%',
      minWidth: '7%',
      showFilter: true,
    },
    {
      header: 'Table Name',
      abbreviation: 'Table Name',
      value: 'tableName',
      dataType: 'string',
      width: '15%',
      checked: true,
      minWidth: '7%',
      showFilter: true,
    },
    {
      header: 'Change Type Name',
      abbreviation: 'Change Type Name',
      value: 'changeTypeName',
      dataType: 'string',
      input: '',
      width: '12%',
      minWidth: '7%',
      checked: true,
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Property Name',
      abbreviation: 'Property Name',
      value: 'propertyName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '12%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },

    {
      header: 'Original Value',
      abbreviation: 'Original Value',
      value: 'originalValue',
      dataType: 'string',
      input: '',
      checked: true,
      width: '12%',
      minWidth: '4%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'New Value',
      abbreviation: 'New Value',
      value: 'newValue',
      dataType: 'string',
      input: '',
      checked: true,
      width: '12%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Changed By',
      abbreviation: 'Changed By',
      value: 'changedBy',
      dataType: 'string',
      input: '',
      checked: true,
      width: '12%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Change Time',
      abbreviation: 'Change Time',
      value: 'changeTime',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '8%',
      isActive: false,
      showFilter: true,
    },
  ],

  RolesColumnHeader: [
    {
      header: '',
      abbreviation: 'Actions',
      value: 'actions',
      dataType: '',
      input: '',
      checked: true,
      width: '9.15%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
    },
    {
      header: 'Role Name',
      abbreviation: 'Role Name',
      value: 'roleName',
      dataType: 'string',
      input: '',
      width: '20%',
      minWidth: '20%',
      checked: true,
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Creation Time',
      abbreviation: 'created at',
      value: 'created',
      dataType: 'date',
      input: '',
      width: '15%',
      minWidth: '15%',
      checked: true,
      isActive: false,
      showFilter: true,
    },
    {
      header: '',
      abbreviation: '',
      value: '',
      dataType: '',
      input: '',
      checked: true,
      showFilter: false,
    },
  ],

  UserColumnHeader: [
    {
      header: 'Actions',
      abbreviation: 'Actions',
      value: 'actions',
      dataType: 'blank',
      input: '',
      checked: true,
      width: '9%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
    },
    {
      header: 'User Name',
      abbreviation: 'User Name',
      value: 'userName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'First Name',
      abbreviation: 'Name',
      value: 'name',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Last Name',
      abbreviation: 'Surname',
      value: 'surname',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Roles',
      abbreviation: 'Roles',
      value: 'roles',
      dataType: 'string',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Email Address',
      abbreviation: 'Email Address',
      value: 'emailAddress',
      dataType: 'string',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Email Verified',
      abbreviation: 'Email Verified',
      value: 'isEmailConfirmed',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '9%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      isCustomColumn: true,
      // showIcons : true,
    },
    {
      header: 'Active',
      abbreviation: 'Active',
      value: 'isActive',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '6%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      isCustomColumn: true,
      //showIcons : true,
    },
    {
      header: 'Last Login',
      abbreviation: 'Last Login',
      value: 'lastLoginTime',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Creation Time',
      abbreviation: 'Creation Time',
      value: 'creationTime',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
  ],

  AuditColumnHeader: [
    {
      header: '',
      abbreviation: 'Actions',
      value: 'actions',
      dataType: 'blank',
      input: '',
      checked: true,
      width: '3%',
      minWidth: '3%',
      isActive: false,
      showFilter: false,
    },
    {
      header: '',
      abbreviation: 'User Name',
      value: 'user',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '3%',
      minWidth: '3%',
      isActive: false,
      showFilter: true,
      isCustomColumn: true,
      // showIcons:true,
    },
    {
      header: 'Username',
      abbreviation: 'Name',
      value: 'userName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '11%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Service',
      abbreviation: 'Surname',
      value: 'serviceName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '11%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Action',
      abbreviation: 'Roles',
      value: 'methodName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '13%',
      minWidth: '9%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Duration',
      abbreviation: 'Email Address',
      value: 'executionDuration',
      dataType: 'string',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'IpAddress',
      abbreviation: 'Email Verified',
      value: 'clientIpAddress',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Client',
      abbreviation: 'Active',
      value: 'clientName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '6%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Browser',
      abbreviation: 'Last Login',
      value: 'browserInfo',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Time',
      abbreviation: 'Creation Time',
      value: 'executionTime',
      dataType: 'date',
      input: '',
      checked: true,
      width: '13.2%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
  ],

  LoginAttemptsColumnHeader: [
    {
      header: 'IP address',
      abbreviation: 'IP address',
      value: 'ipAddress',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Client',
      abbreviation: 'Client',
      value: 'client',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Browser',
      abbreviation: 'Browser',
      value: 'browser',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Time',
      abbreviation: 'Time',
      value: 'time',
      dataType: 'date',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Result',
      abbreviation: 'Result',
      value: 'result',
      dataType: 'blank',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
    },
  ],

  TenantsColumnHeader: [
    {
      header: '',
      abbreviation: 'Actions',
      value: 'actions',
      dataType: '',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
    },
    {
      header: 'Tenancy Code Name ',
      abbreviation: 'Tenancy Code Name',
      value: 'tenancyName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Tenant Name',
      abbreviation: 'Tenant Name',
      value: 'name',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      showFilter: true,
    },
    {
      header: 'Monthly Minimum',
      abbreviation: 'Monthly Minimum',
      value: 'monthlyMinimum',
      dataType: 'number',
      input: '',
      checked: true,
      width: '14%',
      minWidth: '5%',
      showFilter: true,
    },
    // {
    //   header: 'Edition',
    //   abbreviation: 'Edition',
    //   value: 'editionDisplayName',
    //   dataType: 'string',
    //   input: '',
    //   checked: true,
    //   width: '10%',
    //   minWidth: '5%',
    //   isActive: false,
    // },
    // {
    //   header: 'Subscription end date',
    //   abbreviation: 'Subscription end date',
    //   value: 'subscriptionEndDateUtc',
    //   dataType: 'date',
    //   input: '',
    //   checked: true,
    //   width: '10%',
    //   minWidth: '5%',
    //   isActive: false,
    // },
    {
      header: 'Active',
      abbreviation: 'Active',
      value: 'isActive',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '6%',
      minWidth: '5%',
      showFilter: true,
      isCustomColumn: true,
    },
    {
      header: 'Creation Time',
      abbreviation: 'Creation Time',
      value: 'creationTime',
      dataType: 'date',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '5%',
      showFilter: true,
    },
    {
      header: 'Payment Configuration Status',
      abbreviation: 'Payment Configuration Status',
      value: 'paymentMethodConfigured',
      dataType: 'blank',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '5%',
      showFilter: false,
    },
  ],
  MassNotificationsHeaders: [
    {
      header: 'Message',
      abbreviation: ' Message ',
      value: 'data',
      dataType: 'string',
      input: '',
      checked: true,
      width: '30%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: ' Severity ',
      abbreviation: '  Severity  ',
      value: 'severity',
      dataType: 'blank',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
    },
    {
      header: 'Last modification time',
      abbreviation: 'Last modification time',
      value: 'creationTime',
      dataType: 'date',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Published',
      abbreviation: 'Is Published ',
      value: 'isPublished',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      isCustomColumn: true,
      //showIcons: true,
    },
    {
      header: ' User ',
      abbreviation: ' User  ',
      value: 'userName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '18%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: ' Target Notifiers',
      abbreviation: ' Target Notifiers  ',
      value: 'targetNotifiers',
      dataType: 'string',
      input: '',
      checked: true,
      width: '17.15%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
  ],
  WebhookColumnHeader: [
    {
      header: '',
      abbreviation: 'details',
      value: 'details',
      dataType: '',
      input: '',
      checked: true,
      width: '8%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
      showSort: false,
    },
    {
      header: 'Active',
      abbreviation: 'Active',
      value: 'isActive',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      isCustomColumn: true,
      showSort: true,
    },
    {
      header: 'Webhook Endpoint',
      abbreviation: 'Webhook Endpoint',
      value: 'webhookUri',
      dataType: 'string',
      input: '',
      checked: true,
      width: '65%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Webhook Events',
      abbreviation: 'Webhook Events',
      value: 'webhooks',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20.1%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
  ],
  VideoCompletedApiLogsColumnHeader: [
    {
      header: '',
      abbreviation: '',
      value: 'check',
      dataType: 'boolean',
      input: '',
      checked: true,
      width: '3%',
      minWidth: '3%',
      isActive: false,
      isHeaderCheckBox: false,
      showFilter: false,
      isCustomColumn: true,
    },
    {
      header: 'Logs',
      abbreviation: 'Logs',
      value: 'logs',
      dataType: 'blank',
      input: '',
      checked: true,
      width: '5%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
      isCustomColumn: true,
    },
    {
      header: 'Session',
      abbreviation: 'AR #',
      value: 'ar',
      dataType: 'string',
      input: '',
      checked: true,
      width: '7%',
      minWidth: '7%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Environment',
      abbreviation: 'Environment',
      value: 'environment',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '4%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Type',
      abbreviation: 'Type',
      value: 'type',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '10%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Response Code',
      abbreviation: 'Response Code',
      value: 'responseCode',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Creation Time',
      abbreviation: 'created at',
      value: 'creationTime',
      dataType: 'date',
      input: '',
      width: '15%',
      minWidth: '10%',
      checked: true,
      isActive: false,
      showFilter: true,
    },
    {
      header: 'Video Complete API URL',
      abbreviation: 'Video Complete API URL',
      value: 'videoCompleteApiURL',
      dataType: 'string',
      input: '',
      width: '15%',
      minWidth: '10%',
      checked: true,
      isActive: false,
      showFilter: true,
    }
  ],
  WebhookDetailsHeader: [
    {
      header: 'Actions',
      abbreviation: 'Actions',
      value: 'actions',
      dataType: '',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '10%',
      isActive: false,
      showFilter: false,
      showSort: false,
    },
    {
      header: 'Webhook Event',
      abbreviation: 'Webhook Event',
      value: 'webhookName',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Webhook Event Id',
      abbreviation: 'Webhook Event Id',
      value: 'webhookEventId',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Creation Time',
      abbreviation: 'created at',
      value: 'creationTime',
      dataType: 'date',
      input: '',
      width: '18%',
      minWidth: '15%',
      checked: true,
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Http Status Code',
      abbreviation: 'responseStatusCode',
      value: 'webhookUri',
      dataType: 'string',
      input: '',
      checked: true,
      width: '9%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Response',
      abbreviation: 'Response',
      value: 'response',
      dataType: 'string',
      input: '',
      checked: true,
      width: '12%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
      showSort: false,
    },
    {
      header: 'Data',
      abbreviation: 'Data',
      value: 'data',
      dataType: 'string',
      input: '',
      checked: true,
      width: '21.1%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
      showSort: true,
    },
  ],
  ViewEventsHeader: [
    {
      header: 'Actions',
      abbreviation: 'Actions',
      value: 'actions',
      dataType: '',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: false,
      showSort: false,
    },
    {
      header: 'Webhook Subscription Id	',
      abbreviation: 'Webhook Subscription Id',
      value: 'webhookSubscriptionId',
      dataType: 'string',
      input: '',
      checked: true,
      width: '20%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Webhook Endpoint',
      abbreviation: 'Webhook Endpoint',
      value: 'webhookUri',
      dataType: 'string',
      input: '',
      checked: true,
      width: '24%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Creation Time',
      abbreviation: 'created at',
      value: 'creationTime',
      dataType: 'date',
      input: '',
      width: '20%',
      minWidth: '15%',
      checked: true,
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Http Status Code',
      abbreviation: 'Http Status Code',
      value: 'responseStatusCode',
      dataType: 'string',
      input: '',
      checked: true,
      width: '11%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Response',
      abbreviation: 'Response',
      value: 'response',
      dataType: 'string',
      input: '',
      checked: true,
      width: '15.1%',
      minWidth: '9%',
      isActive: false,
      showFilter: false,
      showSort: false,
    },
  ],
  SurveyDialogHistoryHeaders: [
    {
      header: 'Number',
      abbreviation: 'Number',
      value: 'number',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Questions',
      abbreviation: 'Questions',
      value: 'question',
      dataType: 'string',
      input: '',
      checked: true,
      width: '60%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Selected Option',
      abbreviation: 'Selected Option',
      value: 'selectedOption',
      dataType: 'string',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Answers',
      abbreviation: 'Answers',
      value: 'answers',
      dataType: 'string',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
  ],
  QuizDialogHistoryHeaders: [
    {
      header: 'Number',
      abbreviation: 'Number',
      value: 'number',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Questions',
      abbreviation: 'Questions',
      value: 'question',
      dataType: 'string',
      input: '',
      checked: true,
      width: '60%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Selected Option',
      abbreviation: 'Selected Option',
      value: 'selectedOption',
      dataType: 'string',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Answers',
      abbreviation: 'Answers',
      value: 'answers',
      dataType: 'string',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
  ],
  IviDialogHistoryHeaders: [
    {
      header: 'Number',
      abbreviation: 'Number',
      value: 'number',
      dataType: 'string',
      input: '',
      checked: true,
      width: '10%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Questions',
      abbreviation: 'Questions',
      value: 'question',
      dataType: 'string',
      input: '',
      checked: true,
      width: '60%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Selected Option',
      abbreviation: 'Selected Option',
      value: 'selectedOption',
      dataType: 'string',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
    {
      header: 'Answers',
      abbreviation: 'Answers',
      value: 'answers',
      dataType: 'string',
      input: '',
      checked: true,
      width: '15%',
      minWidth: '5%',
      isActive: false,
      showFilter: true,
      showSort: true,
    },
  ],
  RowsPerPage: [20, 50, 100, 500],
  BillingRowPerPage: [50, 100, 200, 500],
  ResourceRowPerPage: [12, 24, 36],
  LimitPerPage: 20,
  MaxCount: 86400000,
  commissionsPermittedUserId: 260,
};
export interface CustomColumn {
  name: string;
  cellElement: any;
}

export interface Paginator {
  first: number,
  rows: number
}
